apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      nodePort: 30036   # port exposed at node
      port: 8002        # port exposed at service
      targetPort: 80    # port exposed at the container
  type: NodePort


# minikube ip - IP 
# curl -X GET $(minikube ip):nodePort
