apiVersion: v1
kind: Service
metadata:
  name: my-service-nodeport-2
spec:
  selector:
    app: nginx-2
  ports:
    - protocol: TCP
      nodePort: 30037   # port exposed at node
      port: 8002        # port exposed at service
      targetPort: 80    # port exposed at the container
  type: NodePort

# minikube ip - IP 
# curl -X GET $(minikube ip):nodePort
