apiVersion: v1
kind: Service
metadata:
  name: my-service-2
spec:
  selector:
    app: nginx-2
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  externalIPs:
    - 192.168.99.100
